### PR TITLE
Desktop file

### PR DESCRIPTION
**Pull request by bkmgit**
https://github.com/nuclear868/mattermost-qt/issues/8

### CODE REVIEW

**Comment by nuclear868** [comment]
Good icons. Some ideas came to me about them:
- I will try to make QT read an icon directly from .svg file. Because, tray icons have different dimensions, depending on deskotp settings
- It will be great to have icons for light and dark color scheme, so that they can be chosen from the client settings
- It will be great to have different sets of icons, containing a number from 1 to 9 in the bottom right corner - i did something similar in the icon.ico files - for the size 24x24, which I'm testing now. I have a plan to replace them with svg, because scaling is easier.

**Comment by bkmgit** [comment]
Why do you need the numbers? Expect most desktops will use SVG.

**Comment by nuclear868** [comment]
In the tray icon, number indicate the count of channels for which there are new messages. There are different icons for the different numbers from 1 to 9 (and icon with no number). Now it it is implemented for the icons in icon.ico files (there are multiple icons (layers) in each .ico file, for different sizes. it is implemented only for the 24x24 size, so it may not be visible on all platforms).

I plan to replace them with an .svg icon, because it is easier to be edited. It will be based on these icons, with some elements slightly arranged, so that there will be place for the numbers in order to be visible in smaller sizes.

**Comment by bkmgit** [comment]
The desktop file uses QTM  logo, but have not changed others. Probably this can be done later?

**Comment by nuclear868** [comment]
Yes, it is ok. Based on these icons, I will fix the tray icons.

**Pull request merged**
